/* Pedro Zanatta — interaction engine + project showcase */
document.addEventListener('DOMContentLoaded',function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
const cur=$('#cur'),ring=$('#cur-ring');let mx=innerWidth/2,my=innerHeight/2,rx=mx,ry=my;
document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;if(cur){cur.style.left=mx+'px';cur.style.top=my+'px';}},{passive:true});
(function loop(){rx+=(mx-rx)*.12;ry+=(my-ry)*.12;if(ring){ring.style.left=rx+'px';ring.style.top=ry+'px';}requestAnimationFrame(loop)})();
document.addEventListener('mouseleave',()=>{if(cur)cur.style.opacity=0;if(ring)ring.style.opacity=0});document.addEventListener('mouseenter',()=>{if(cur)cur.style.opacity=1;if(ring)ring.style.opacity=1});

/* Featured projects — only projects verified in Pedro's GitHub repositories */
const projects=[
 {n:'01',name:'MS Manager AI',type:'AI · SOFTWARE',desc:'Projeto de software com foco em gestão e recursos de inteligência artificial. Um dos projetos mais relevantes para mostrar visão de produto, tecnologia e experimentação.',tags:['AI','Software','Automation'],url:'https://github.com/ZanattaDev/manager-ai',featured:true},
 {n:'02',name:'Smart Allocation Engine',type:'ALGORITHMS · DATA',desc:'Projeto focado em lógica de alocação inteligente, mostrando interesse por regras, dados e tomada de decisão automatizada.',tags:['Algorithms','Data','Logic'],url:'https://github.com/ZanattaDev/SmartAllocationEngine'},
 {n:'03',name:'Mercado Solidário',type:'WEB · SYSTEM',desc:'Projeto de sistema que combina aplicação, experiência web e lógica de negócio. O código principal é privado, então o portfólio identifica isso claramente.',tags:['Web','System','Product'],url:'https://github.com/ZanattaDev/Mercado-Solidario',private:true},
 {n:'04',name:'Governo App Site',type:'WEB · INTERFACE',desc:'Projeto web voltado para interface e apresentação de um produto digital, reforçando sua experiência além do backend.',tags:['HTML','CSS','Web'],url:'https://github.com/ZanattaDev/Governo-App-Site'},
 {n:'05',name:'Detector de Nuvens',type:'HARDWARE · IOT',desc:'Experimento com Arduino para detecção de nuvens. Mostra que sua curiosidade vai de software até hardware e eletrônica.',tags:['Arduino','C/C++','IoT'],url:'https://github.com/ZanattaDev/codigo-para-detectar-nuvem-com-arduino'},
 {n:'06',name:'FiveM / Sistemas RP',type:'SYSTEMS · LUA',desc:'Experiência prática criando scripts, HUDs, integrações, telefone e sistemas para servidores base Creative.',tags:['Lua','FiveM','Systems'],url:'https://github.com/ZanattaDev'}
];
const oldProjects=$('#projects');
if(oldProjects){
 const showcase=document.createElement('section');showcase.id='featured-projects';showcase.className='section';
 showcase.innerHTML=`<div class="wrap"><div class="sec-lbl">03 · Projetos em destaque</div><div class="project-head"><div><h2 class="sec-h">Construí <em>isso.</em></h2><p class="sec-sub">Menos exercícios. Mais coisas que mostram como eu penso, experimento e transformo ideias em software.</p></div><div class="project-count"><b>06</b><span>projetos selecionados</span></div></div><div class="project-filters" role="tablist"><button class="active" data-filter="all">TODOS</button><button data-filter="AI">AI</button><button data-filter="WEB">WEB</button><button data-filter="SYSTEMS">SYSTEMS</button><button data-filter="IOT">IOT</button><button data-filter="AUTOMATION">AUTOMATION</button></div><div class="featured-grid"></div><div class="all-github"><span>Quer ver os experimentos menores também?</span><a href="https://github.com/ZanattaDev" target="_blank" rel="noreferrer">Explorar todos os repositórios ↗</a></div></div>`;
 oldProjects.replaceWith(showcase);
 const grid=showcase.querySelector('.featured-grid');
 function render(filter='all'){
  grid.innerHTML=projects.filter(p=>filter==='all'||p.type.includes(filter)||p.tags.some(t=>t.toUpperCase()===filter)).map((p,i)=>`<a class="featured-card ${p.featured?'featured-main':''} rev in" href="${p.url}" target="_blank" rel="noreferrer" data-category="${p.type}"><div class="featured-top"><span>${p.n}</span><span>${p.private?'PRIVATE REPO':'OPEN SOURCE'} · ↗</span></div><div class="featured-content"><span class="featured-type">${p.type}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="featured-arrow">↗</div></a>`).join('');
  if(!reduce) $$('.featured-card').forEach(card=>{card.classList.add('dev-interactive-card');card.addEventListener('pointermove',cardTilt);card.addEventListener('pointerleave',()=>card.style.transform='')});
 }
 render();
 showcase.querySelectorAll('.project-filters button').forEach(btn=>btn.addEventListener('click',()=>{showcase.querySelectorAll('.project-filters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter)}));
}

const nav=$('#nav'),sections=$$('section[id]'),links=$$('.nav-links a');
function navUpdate(){if(nav)nav.classList.toggle('scrolled',scrollY>40);let id='';sections.forEach(s=>{if(scrollY>=s.offsetTop-140)id=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));}addEventListener('scroll',navUpdate,{passive:true});navUpdate();
const style=document.createElement('style');style.textContent=`
#dev-scroll-progress{position:fixed;top:0;left:0;height:1px;width:0;background:linear-gradient(90deg,#777,#fff);box-shadow:0 0 10px #fff;z-index:10001;pointer-events:none}
#dev-canvas{mix-blend-mode:screen}.dev-interactive-card{position:relative;overflow:hidden;transform-style:preserve-3d;transition:transform .35s cubic-bezier(.16,1,.3,1),border-color .3s,box-shadow .3s!important}.dev-interactive-card:after{content:"";position:absolute;inset:0;pointer-events:none;border-radius:inherit;background:radial-gradient(circle at var(--spot-x,50%) var(--spot-y,50%),rgba(255,255,255,.08),transparent 35%);opacity:0;transition:opacity .25s}.dev-interactive-card:hover:after{opacity:1}.project-focus{border-color:rgba(255,255,255,.18)!important;box-shadow:0 18px 55px rgba(0,0,0,.28)!important}#home .wrap{transform:translate3d(var(--hero-x,0),var(--hero-y,0),0);transition:transform .25s ease-out}.section{--section-shift:0px}.section>.wrap{transform:translateY(var(--section-shift));transition:transform .15s linear}
.project-head{display:flex;justify-content:space-between;align-items:end;gap:2rem;margin-bottom:2rem}.project-count{display:flex;align-items:baseline;gap:.55rem;font-family:var(--mono);color:#444}.project-count b{font:400 2rem var(--serif);color:#bbb}.project-count span{font-size:.55rem;text-transform:uppercase;letter-spacing:.1em}.project-filters{display:flex;gap:.35rem;flex-wrap:wrap;margin-bottom:1rem}.project-filters button{font:500 .55rem var(--mono);letter-spacing:.08em;color:#555;border:1px solid var(--border);border-radius:100px;padding:.42rem .65rem;background:transparent;cursor:pointer;transition:.25s}.project-filters button:hover,.project-filters button.active{color:#ddd;border-color:#666;background:#111}.featured-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:var(--border);border:1px solid var(--border);border-radius:12px;overflow:hidden}.featured-card{min-height:290px;background:#090909;color:inherit;text-decoration:none;padding:1.35rem;display:flex;flex-direction:column;position:relative;transition:background .35s,transform .35s!important}.featured-card:hover{background:#101010}.featured-main{grid-column:span 2;min-height:350px;background:radial-gradient(circle at 80% 20%,rgba(255,255,255,.055),transparent 35%),#090909}.featured-top{display:flex;justify-content:space-between;font:500 .53rem var(--mono);color:#444}.featured-content{margin-top:auto;max-width:650px}.featured-type{font:500 .55rem var(--mono);letter-spacing:.14em;color:#626262}.featured-content h3{font:400 clamp(1.6rem,3vw,2.7rem) var(--serif);margin:.45rem 0 .6rem;color:#e0ddd6}.featured-card:not(.featured-main) .featured-content h3{font-size:1.65rem}.featured-content p{font-size:.74rem;line-height:1.75;color:#5c5c5c;max-width:570px}.featured-arrow{position:absolute;right:1.25rem;bottom:1.2rem;color:#444;font:500 .9rem var(--mono);transition:.3s}.featured-card:hover .featured-arrow{color:#ddd;transform:translate(4px,-4px)}.all-github{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1.1rem 0;font:500 .58rem var(--mono);color:#444}.all-github a{color:#888;transition:.3s}.all-github a:hover{color:#ddd}
@media(max-width:800px){.project-head{align-items:start;flex-direction:column}.featured-main{grid-column:span 1}.featured-grid{grid-template-columns:1fr}.all-github{align-items:start;flex-direction:column}.project-count{display:none}}
@media(hover:none){.dev-interactive-card{transform:none!important}.section>.wrap{transform:none!important}}
`;$('head').appendChild(style);
const progress=document.createElement('div');progress.id='dev-scroll-progress';document.body.appendChild(progress);
function scrollFx(){let max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+'%';if(!reduce)$$('.section').forEach(s=>{let r=s.getBoundingClientRect(),d=(r.top+r.height/2-innerHeight/2)/innerHeight;s.style.setProperty('--section-shift',(d*4).toFixed(2)+'px')});}addEventListener('scroll',scrollFx,{passive:true});scrollFx();
if(!reduce){const c=document.createElement('canvas');c.id='dev-canvas';Object.assign(c.style,{position:'fixed',inset:0,width:'100%',height:'100%',pointerEvents:'none',zIndex:0,opacity:.32});document.body.prepend(c);const x=c.getContext('2d');let p=[];function size(){let d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);p=Array.from({length:Math.min(64,Math.max(25,innerWidth/24))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,r:Math.random()+.2}))}size();addEventListener('resize',size,{passive:true});(function draw(){x.clearRect(0,0,innerWidth,innerHeight);p.forEach(a=>{a.x+=a.vx;a.y+=a.vy;if(a.x<0||a.x>innerWidth)a.vx*=-1;if(a.y<0||a.y>innerHeight)a.vy*=-1;x.fillStyle='rgba(255,255,255,.35)';x.beginPath();x.arc(a.x,a.y,a.r,0,7);x.fill()});for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){let a=p[i],b=p[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<100){x.strokeStyle='rgba(255,255,255,'+(.045*(1-d/100))+')';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke()}}requestAnimationFrame(draw)})()}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.08});$$('.rev').forEach(e=>observer.observe(e));
const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('.sk-fill',e.target).forEach((b,i)=>setTimeout(()=>b.style.width=b.dataset.w+'%',i*90));$$('.sk-track i',e.target).forEach((b,i)=>setTimeout(()=>b.style.width=b.dataset.w+'%',i*90));so.unobserve(e.target)}}),{threshold:.15});$$('.sk-grid').forEach(e=>so.observe(e));
function cardTilt(e){let el=e.currentTarget,r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;el.style.setProperty('--spot-x',(x/r.width*100)+'%');el.style.setProperty('--spot-y',(y/r.height*100)+'%');el.style.transform=`perspective(850px) rotateX(${-(y/r.height-.5)*2.5}deg) rotateY(${(x/r.width-.5)*3}deg) translateY(-3px)`}
if(!reduce)$$('.btn-s,.soc,.nav-pill').forEach(el=>{el.addEventListener('pointermove',e=>{let r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width,y=(e.clientY-r.top-r.height/2)/r.height;el.style.transform=`translate(${x*6}px,${y*4}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
if(!reduce)$$('.proj-item,.sk-cat,.acard,.srv-cell').forEach(el=>{el.classList.add('dev-interactive-card');el.addEventListener('pointermove',cardTilt);el.addEventListener('pointerleave',()=>el.style.transform='')});
const glyph='01<>/{}[]$#@';$$('.sec-lbl').forEach(el=>el.addEventListener('mouseenter',()=>{if(el.dataset.busy)return;el.dataset.busy=1;let text=el.textContent,n=0,t=setInterval(()=>{el.textContent=text.split('').map((c,i)=>i<n?c:glyph[Math.floor(Math.random()*glyph.length)]).join('');if(++n>text.length){clearInterval(t);el.textContent=text;delete el.dataset.busy}},30)}));
const form=$('#contact-form');if(form)form.addEventListener('submit',function(e){e.preventDefault();const btn=this.querySelector('button[type=submit]');const data={nome:this.querySelector('[name=nome]')?.value||'',email:this.querySelector('[name=email]')?.value||'',assunto:this.querySelector('[name=assunto]')?.value||'',mensagem:this.querySelector('[name=mensagem]')?.value||''};const url='https://script.google.com/macros/s/AKfycbwN-zFlL0hW4pSOD88aGbFYLBOiS5CUeozCXf9GunbK5yIfa1sPzO2W6z1jVBQt941v/exec';if(btn)btn.textContent='Enviando…';fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(()=>{alert('Mensagem enviada com sucesso!');form.reset();if(btn)btn.textContent='Enviar'}).catch(()=>{alert('Ops, erro ao enviar.');if(btn)btn.textContent='Enviar'});});
});
